# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: admin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x64min.proto\x12\x05\x61\x64min\"#\n\x10\x43losePollRequest\x12\x0f\n\x07poll_id\x18\x01 \x01(\x05\"#\n\x11\x43losePollResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2N\n\x0c\x41\x64minService\x12>\n\tClosePoll\x12\x17.admin.ClosePollRequest\x1a\x18.admin.ClosePollResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLOSEPOLLREQUEST']._serialized_start=22
  _globals['_CLOSEPOLLREQUEST']._serialized_end=57
  _globals['_CLOSEPOLLRESPONSE']._serialized_start=59
  _globals['_CLOSEPOLLRESPONSE']._serialized_end=94
  _globals['_ADMINSERVICE']._serialized_start=96
  _globals['_ADMINSERVICE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
